apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
  - name: shop-config
    namespace: shop
    behavior: merge
    literals:
      - GREETING=hello from dev